# Generated by Django 4.2.1 on 2024-07-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconnection',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('a', 'accepted'), ('r', 'rejected')], default='p', max_length=10),
        ),
    ]
