# Generated by Django 4.2.1 on 2024-07-25 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_userconnection_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconnection',
            name='first_user',
        ),
        migrations.RemoveField(
            model_name='userconnection',
            name='second_user',
        ),
        migrations.AddField(
            model_name='userconnection',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userconnection',
            name='target_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
